//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechMarket.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SGDFleaMarketEntities : DbContext
    {
        public SGDFleaMarketEntities()
            : base("name=SGDFleaMarketEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tbl_BannerSlide> tbl_BannerSlide { get; set; }
        public virtual DbSet<tbl_Channel> tbl_Channel { get; set; }
        public virtual DbSet<tbl_Coin> tbl_Coin { get; set; }
        public virtual DbSet<tbl_Color> tbl_Color { get; set; }
        public virtual DbSet<tbl_CPU> tbl_CPU { get; set; }
        public virtual DbSet<tbl_DateOfHire> tbl_DateOfHire { get; set; }
        public virtual DbSet<tbl_Device> tbl_Device { get; set; }
        public virtual DbSet<tbl_Manufacturer> tbl_Manufacturer { get; set; }
        public virtual DbSet<tbl_Messages> tbl_Messages { get; set; }
        public virtual DbSet<tbl_Screensize> tbl_Screensize { get; set; }
        public virtual DbSet<tbl_TypeOfDevice> tbl_TypeOfDevice { get; set; }
        public virtual DbSet<tbl_Shop> tbl_Shop { get; set; }
        public virtual DbSet<tbl_Account> tbl_Account { get; set; }
        public virtual DbSet<tbl_Report> tbl_Report { get; set; }
        public virtual DbSet<tbl_Evaluete> tbl_Evaluete { get; set; }
        public virtual DbSet<tbl_Product> tbl_Product { get; set; }
        public virtual DbSet<tbl_Images> tbl_Images { get; set; }
    }
}
