//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechMarket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Screensize
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Screensize()
        {
            this.tbl_Product = new HashSet<tbl_Product>();
        }
    
        public int Id { get; set; }
        public string screensize_name { get; set; }
        public Nullable<int> id_device { get; set; }
    
        public virtual tbl_Device tbl_Device { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Product> tbl_Product { get; set; }
    }
}
