//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechMarket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Evaluete
    {
        public int Id { get; set; }
        public Nullable<int> id_customer { get; set; }
        public Nullable<int> star { get; set; }
        public Nullable<int> id_account { get; set; }
        public Nullable<int> id_shop { get; set; }
    
        public virtual tbl_Account tbl_Account { get; set; }
        public virtual tbl_Account tbl_Account1 { get; set; }
        public virtual tbl_Shop tbl_Shop { get; set; }
    }
}
