//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechMarket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Shop
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Shop()
        {
            this.tbl_DateOfHire = new HashSet<tbl_DateOfHire>();
            this.tbl_Evaluete = new HashSet<tbl_Evaluete>();
            this.tbl_Product = new HashSet<tbl_Product>();
        }
    
        public int Id { get; set; }
        public string shop_name { get; set; }
        public string shop_address { get; set; }
        public string shop_introduce { get; set; }
        public string shop_phone { get; set; }
        public string shop_avatar { get; set; }
        public string shop_background { get; set; }
        public Nullable<int> id_account { get; set; }
        public string shop_link { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_DateOfHire> tbl_DateOfHire { get; set; }
        public virtual tbl_Account tbl_Account { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Evaluete> tbl_Evaluete { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Product> tbl_Product { get; set; }
    }
}
