//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechMarket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Report
    {
        public int Id { get; set; }
        public Nullable<int> id_product { get; set; }
        public string typeReport { get; set; }
        public Nullable<int> id_customer { get; set; }
        public Nullable<int> status { get; set; }
    
        public virtual tbl_Product tbl_Product { get; set; }
    }
}
